[build]
  publish = "dist"
  command = "npm run build"
[functions]
  external_node_modules = ["svgo"]
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"